plugins:
  discord_datastore_enabled:
    default: true
    client: true
  discord_bot_token:
    default: ""
  discord_server_id:
    default: ""
    client: true
  discord_bot_channel_id:
    default: ""
  discord_ignore_bot_channel:
    default: true
  discord_bot_command_prefix:
    default: "!"
  discord_bot_status:
    default: "Watching."
  discord_header_image:
    default: ""
    type: upload
    client: true
  discord_invite_url:
    default: ""
    client: true
  discord_messages_before_resync:
    default: 200
  discord_verified_rank:
    default: ""
  discord_rank_name:
    default: ""
    type: list
    client: true
  discord_rank_count:
    default: ""
    type: list
    client: true
  discord_rank_image:
    default: ""
    type: list
    client: true
  discord_rank_badge_id:
    default: ""
    type: list
    client: true