plugins:
  discord_datastore_enabled:
    default: true
    client: true

  discord_server_id:
    default: ""
    client: true
  discord_bot_token:
    default: ""
  discord_bot_channel:
    default: ""

  discord_invite_url:
    default: ""
    client: true

  discord_header_image:
    default: ""
    type: upload
    client: true

  discord_rank_1_id:
      default: ""
      client: true
  discord_rank_1_count:
      default: ""
      client: true
  discord_rank_1_image:
      default: ""
      type: upload
      client: true
  discord_rank_1_badge:
      default: ""
      client: true

  discord_rank_2_id:
      default: ""
      client: true
  discord_rank_2_count:
      default: ""
      client: true
  discord_rank_2_image:
      default: ""
      type: upload
      client: true
  discord_rank_2_badge:
      default: ""
      client: true

  discord_rank_3_id:
      default: ""
      client: true
  discord_rank_3_count:
      default: ""
      client: true
  discord_rank_3_image:
      default: ""
      type: upload
      client: true
  discord_rank_3_badge:
      default: ""
      client: true

  discord_rank_4_id:
      default: ""
      client: true
  discord_rank_4_count:
      default: ""
      client: true
  discord_rank_4_image:
      default: ""
      type: upload
      client: true
  discord_rank_4_badge:
      default: ""
      client: true

  discord_rank_5_id:
      default: ""
      client: true
  discord_rank_5_count:
      default: ""
      client: true
  discord_rank_5_image:
      default: ""
      type: upload
      client: true
  discord_rank_5_badge:
      default: ""
      client: true

  discord_rank_6_id:
      default: ""
      client: true
  discord_rank_6_count:
      default: ""
      client: true
  discord_rank_6_image:
      default: ""
      type: upload
      client: true
  discord_rank_6_badge:
      default: ""
      client: true

  discord_rank_7_id:
      default: ""
      client: true
  discord_rank_7_count:
      default: ""
      client: true
  discord_rank_7_image:
      default: ""
      type: upload
      client: true
  discord_rank_7_badge:
      default: ""
      client: true

  discord_rank_8_id:
      default: ""
      client: true
  discord_rank_8_count:
      default: ""
      client: true
  discord_rank_8_image:
      default: ""
      type: upload
      client: true
  discord_rank_8_badge:
      default: ""
      client: true

  discord_rank_9_id:
      default: ""
      client: true
  discord_rank_9_count:
      default: ""
      client: true
  discord_rank_9_image:
      default: ""
      type: upload
      client: true
  discord_rank_9_badge:
      default: ""
      client: true